-- noinspection SqlResolveForFile

-- @formatter:off
MERGE INTO USER (ID, USERNAME, MAIL, ADDRESS, ACTIVE) KEY (ID) VALUES (1, 'User', 'user@mail.com', 'Testna Ulica 1', true);
MERGE INTO DELIVERER (ID, CODE, FIRST_NAME, LAST_NAME, ACTIVE) KEY (ID) VALUES (1, 'DEL0', 'Ivan', 'Ivanic', true);
MERGE INTO ORDERS (ID, CODE, DELIVERER_ID, USER_ID, CREATED_TIME, DELIVERY_DATETIME, ADDRESS, PRICE, CASH_ON_DELIVERY, DELIVERED, ADDITIONAL_INFO, ACTIVE) KEY (ID) VALUES (1, 'ORD0', 1, 1, '2019-07-10 13:50:45', '2019-07-10 13:50:45', 'Testna Ulica 1', 200.00, 1, 1, 'nema nekih info', true);
MERGE INTO PRODUCT (ID, CODE, NAME, PRICE, ACTIVE) KEY (ID) VALUES (1, 'PRO0', 'Proizvod', 100.00, true);
MERGE INTO RECIPE (ID, CODE, NAME, TEXT, CREATED_TIME, ACTIVE) KEY (ID) VALUES (1, 'REC0', 'Recept', 'Napravi bilo sta', '2019-07-10 13:50:45', true);
-- @formatter:on